In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
matches = pd.read_csv('data/matches.csv')
deliveries = pd.read_csv('data/deliveries.csv')

# First look
print("=== MATCHES ===")
print(matches.shape)
matches.head()

=== MATCHES ===
(1095, 20)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [2]:
print(matches.info())
print("\n")
print(matches.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB
None


                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [3]:
print("=== DELIVERIES ===")
print(deliveries.shape)
deliveries.head()

=== DELIVERIES ===
(260920, 17)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [4]:
print(deliveries.info())
print("\n")
print(deliveries.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB
None


           match_id         inning           over           ball  \
count  2.609200e+05  260920.000000  260920.000000  260920.000000
mean   9.070665e+05       1.483531       9.197677       3.624486
std    3.679913e+05       0.502643       5.683484       1.814920
min    3.359820e+05       1.000000       0.000000       1.000000
25%    5.483340e+05       1.000000       4.000000       2.000000
50%    9.809670e+05       1.000000       9.000000       4.000000
75%    1.254066e+06       2.000000      14.000000       5.000000
max    1.426312e+06       6.000000      19.000000      11.000000

        batsman_runs     extra_runs     total_runs      is_wicket
count  260920.000000  260920.000000  260920.000000  260920.000000
mean        1.265001       0.067806       1.332807       0.049632
std         1.639298       0.343265       1.626416       0.217184
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         1.000000       0.000000       1.000000       0.000000
75%         1.000000       0.000000       1.000000       0.000000
max         6.000000       7.000000       7.000000       1.000000

In [5]:
print(matches['season'].value_counts().sort_index())

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
Name: count, dtype: int64

In [6]:
print("=== MATCHES ===")
print(f"Total matches: {len(matches)}")
print(f"\nMissing winners (no-result): {matches['winner'].isna().sum()}")
print(f"DLS-affected matches: {matches['method'].notna().sum()}")
print(f"Super over matches: {(matches['super_over'] == 'Y').sum()}")
print(f"\nSeason dtype: {matches['season'].dtype}")
print(f"Unique seasons: {sorted(matches['season'].unique())}")
print(f"Toss decisions: {matches['toss_decision'].value_counts().to_dict()}")

print("\n=== DELIVERIES ===")
print(f"Total deliveries: {len(deliveries)}")
print(f"Super over deliveries (inning > 2): {(deliveries['inning'] > 2).sum()}")
print(f"Wickets: {deliveries['is_wicket'].sum()}")
print(f"Wicket rate: {deliveries['is_wicket'].mean():.3%}")
print(f"\nExtras breakdown:\n{deliveries['extras_type'].value_counts()}")
print(f"\nDismissal types:\n{deliveries['dismissal_kind'].value_counts()}")

=== MATCHES ===
Total matches: 1095

Missing winners (no-result): 5
DLS-affected matches: 21
Super over matches: 14

Season dtype: object
Unique seasons: ['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022', '2023', '2024']
Toss decisions: {'field': 704, 'bat': 391}

=== DELIVERIES ===
Total deliveries: 260920
Super over deliveries (inning > 2): 161
Wickets: 12950
Wicket rate: 4.963%

Extras breakdown:
extras_type
wides      8380
legbyes    4001
noballs    1069
byes        673
penalty       2
Name: count, dtype: int64

Dismissal types:
dismissal_kind
caught                   8063
bowled                   2212
run out                  1114
lbw                       800
caught and bowled         367
stumped                   358
retired hurt               15
hit wicket                 15
obstructing the field       3
retired out                 3
Name: count, dtype: int64

In [7]:
matches['season'] = matches['season'].apply(
    lambda x: int(str(x).split('/')[0])
)
print(matches['season'].value_counts().sort_index())
print(f"Dtype now: {matches['season'].dtype}")

season
2007     58
2009    117
2011     73
2012     74
2013     76
2014     60
2015     59
2016     60
2017     59
2018     60
2019     60
2020     60
2021     60
2022     74
2023     74
2024     71
Name: count, dtype: int64
Dtype now: int64

In [8]:
matches['season'] = matches['season'].apply(
    lambda x: int(str(x).split('/')[0])
)
print(matches['season'].value_counts().sort_index())
print(f"Dtype now: {matches['season'].dtype}")

season
2007     58
2009    117
2011     73
2012     74
2013     76
2014     60
2015     59
2016     60
2017     59
2018     60
2019     60
2020     60
2021     60
2022     74
2023     74
2024     71
Name: count, dtype: int64
Dtype now: int64

In [9]:
before = len(matches)
matches = matches[matches['winner'].notna()]           # drop 5 no-results
matches = matches[matches['method'].isna()]            # drop 21 DLS matches
after = len(matches)
print(f"Dropped {before - after} matches")
print(f"Remaining: {after} matches")

Dropped 26 matches
Remaining: 1069 matches

In [10]:
before = len(deliveries)
deliveries = deliveries[deliveries['inning'] <= 2]
after = len(deliveries)
print(f"Removed {before - after} super over deliveries")
print(f"Remaining: {after} deliveries")

Removed 161 super over deliveries
Remaining: 260759 deliveries

In [11]:
valid_match_ids = set(matches['id'])
deliveries = deliveries[deliveries['match_id'].isin(valid_match_ids)]
print(f"Deliveries after match filter: {len(deliveries)}")

Deliveries after match filter: 256623

In [12]:
# Step 1: Aggregate batting stats per player per match
batting = deliveries.groupby(['match_id', 'batter']).agg(
    runs=('batsman_runs', 'sum'),
    fours=('batsman_runs', lambda x: (x == 4).sum()),
    sixes=('batsman_runs', lambda x: (x == 6).sum()),
).reset_index()

# Step 2: Find dismissed batters to check for ducks
dismissed = deliveries[deliveries['is_wicket'] == 1][['match_id', 'player_dismissed']].copy()
dismissed.columns = ['match_id', 'batter']
dismissed['got_out'] = 1

batting = batting.merge(dismissed, on=['match_id', 'batter'], how='left')
batting['got_out'] = batting['got_out'].fillna(0)
batting['duck'] = ((batting['runs'] == 0) & (batting['got_out'] == 1)).astype(int)

# Step 3: Calculate batting fantasy points
batting['bat_pts'] = (
    batting['runs'] * 0.5 +
    batting['fours'] * 1 +
    batting['sixes'] * 2 +
    (batting['runs'] >= 25).astype(int) * 4 +
    (batting['runs'] >= 50).astype(int) * 8 +
    (batting['runs'] >= 75).astype(int) * 8 +
    (batting['runs'] >= 100).astype(int) * 16 -
    batting['duck'] * 2
)

print(batting[['batter', 'runs', 'fours', 'sixes', 'duck', 'bat_pts']].head(10))
print(f"\nTotal batting entries: {len(batting)}")
print(f"Avg batting pts: {batting['bat_pts'].mean():.2f}")

            batter  runs  fours  sixes  duck  bat_pts
0        AA Noffke     9      1      0     0      5.5
1          B Akhil     0      0      0     1     -2.0
2      BB McCullum   158     10     13     0    151.0
3         CL White     6      0      0     0      3.0
4        DJ Hussey    12      1      0     0      7.0
5        JH Kallis     8      0      1     0      6.0
6       MV Boucher     7      1      0     0      4.5
7  Mohammad Hafeez     5      1      0     0      3.5
8          P Kumar    18      1      2     0     14.0
9         R Dravid     2      0      0     0      1.0

Total batting entries: 16231
Avg batting pts: 15.63

In [13]:
# Step 1: Wickets - run outs credit the fielder, not the bowler
bowl_deliveries = deliveries[
    (deliveries['is_wicket'] == 1) & 
    (~deliveries['dismissal_kind'].isin(['run out', 'retired hurt', 'retired out']))
]

bowling = bowl_deliveries.groupby(['match_id', 'bowler']).agg(
    wickets=('is_wicket', 'sum'),
    lbw_bowled=('dismissal_kind', lambda x: x.isin(['lbw', 'bowled']).sum())
).reset_index()

# Step 2: Maiden overs
over_runs = deliveries.groupby(['match_id', 'bowler', 'over'])['total_runs'].sum().reset_index()
maidens = over_runs[over_runs['total_runs'] == 0].groupby(
    ['match_id', 'bowler']
).size().reset_index(name='maidens')

bowling = bowling.merge(maidens, on=['match_id', 'bowler'], how='left')
bowling['maidens'] = bowling['maidens'].fillna(0)

# Step 3: Calculate bowling fantasy points
bowling['bowl_pts'] = (
    bowling['wickets'] * 25 +
    bowling['lbw_bowled'] * 8 +
    (bowling['wickets'] >= 3).astype(int) * 4 +
    (bowling['wickets'] >= 4).astype(int) * 8 +
    (bowling['wickets'] >= 5).astype(int) * 16 +
    bowling['maidens'] * 12
)

print(bowling[['bowler', 'wickets', 'lbw_bowled', 'maidens', 'bowl_pts']].head(10))
print(f"\nTotal bowling entries: {len(bowling)}")
print(f"Avg bowling pts: {bowling['bowl_pts'].mean():.2f}")

       bowler  wickets  lbw_bowled  maidens  bowl_pts
0   AA Noffke        1           0      0.0      25.0
1  AB Agarkar        3           0      0.0      79.0
2    AB Dinda        2           1      0.0      58.0
3    I Sharma        1           1      0.0      33.0
4   JH Kallis        1           0      0.0      25.0
5   LR Shukla        1           0      0.0      25.0
6  SC Ganguly        2           1      0.0      58.0
7      Z Khan        1           0      0.0      25.0
8       B Lee        1           0      0.0      25.0
9   IK Pathan        2           2      0.0      66.0

Total bowling entries: 7280
Avg bowling pts: 44.44

In [14]:
# Catches (fielder column has the catcher's name)
catches = deliveries[deliveries['dismissal_kind'] == 'caught'].dropna(subset=['fielder'])
catches_grp = catches.groupby(['match_id', 'fielder']).size().reset_index(name='catches')
catches_grp.rename(columns={'fielder': 'player'}, inplace=True)

# Caught and bowled - bowler gets the credit
cab = deliveries[deliveries['dismissal_kind'] == 'caught and bowled'].copy()
cab_grp = cab.groupby(['match_id', 'bowler']).size().reset_index(name='cab_catches')
cab_grp.rename(columns={'bowler': 'player'}, inplace=True)

# Stumpings
stumpings = deliveries[deliveries['dismissal_kind'] == 'stumped'].dropna(subset=['fielder'])
stumpings_grp = stumpings.groupby(['match_id', 'fielder']).size().reset_index(name='stumpings')
stumpings_grp.rename(columns={'fielder': 'player'}, inplace=True)

# Run outs
run_outs = deliveries[deliveries['dismissal_kind'] == 'run out'].dropna(subset=['fielder'])
run_outs_grp = run_outs.groupby(['match_id', 'fielder']).size().reset_index(name='run_outs')
run_outs_grp.rename(columns={'fielder': 'player'}, inplace=True)

# Merge all fielding components
fielding = catches_grp.merge(cab_grp, on=['match_id', 'player'], how='outer')
fielding = fielding.merge(stumpings_grp, on=['match_id', 'player'], how='outer')
fielding = fielding.merge(run_outs_grp, on=['match_id', 'player'], how='outer')
fielding = fielding.fillna(0)

fielding['field_pts'] = (
    fielding['catches'] * 8 +
    fielding['cab_catches'] * 8 +
    fielding['stumpings'] * 12 +
    fielding['run_outs'] * 6
)

print(fielding.head(10))
print(f"\nTotal fielding entries: {len(fielding)}")

   match_id           player  catches  cab_catches  stumpings  run_outs  \
0    335982       AB Agarkar      0.0          0.0        0.0       1.0
1    335982      BB McCullum      1.0          0.0        0.0       0.0
2    335982         CL White      1.0          0.0        0.0       0.0
3    335982        JH Kallis      1.0          0.0        0.0       0.0
4    335982         M Kartik      2.0          0.0        0.0       0.0
5    335982          P Kumar      1.0          0.0        0.0       0.0
6    335982       RT Ponting      2.0          0.0        0.0       0.0
7    335982          WP Saha      1.0          0.0        0.0       0.0
8    335983        IK Pathan      1.0          0.0        0.0       0.0
9    335983  Joginder Sharma      2.0          0.0        0.0       0.0

   field_pts
0        6.0
1        8.0
2        8.0
3        8.0
4       16.0
5        8.0
6       16.0
7        8.0
8        8.0
9       16.0

Total fielding entries: 7531

In [15]:
# Standardise column names for merging
bat_merge = batting[['match_id', 'batter', 'bat_pts']].rename(columns={'batter': 'player'})
bowl_merge = bowling[['match_id', 'bowler', 'bowl_pts']].rename(columns={'bowler': 'player'})
field_merge = fielding[['match_id', 'player', 'field_pts']]

# Outer merge — a player might bat but not bowl, or bowl but not bat
fantasy = bat_merge.merge(bowl_merge, on=['match_id', 'player'], how='outer')
fantasy = fantasy.merge(field_merge, on=['match_id', 'player'], how='outer')
fantasy = fantasy.fillna(0)

fantasy['fantasy_points'] = fantasy['bat_pts'] + fantasy['bowl_pts'] + fantasy['field_pts']

print(f"Total player-match entries: {len(fantasy)}")
print(f"\nFantasy points distribution:")
print(fantasy['fantasy_points'].describe())
print(f"\nTop 10 individual performances:")
print(fantasy.sort_values('fantasy_points', ascending=False).head(10))

Total player-match entries: 21507

Fantasy points distribution:
count    21507.000000
mean        30.369298
std         27.537244
min         -2.000000
25%          8.500000
50%         25.000000
75%         44.500000
max        234.000000
Name: fantasy_points, dtype: float64

Top 10 individual performances:
       match_id         player  bat_pts  bowl_pts  field_pts  fantasy_points
486      336005  Sohail Tanvir      0.0     218.0       16.0           234.0
6815     598027       CH Gayle    170.5      58.0        0.0           228.5
13737   1178394      AS Joseph      0.0     214.0        8.0           222.0
8398     733999   Yuvraj Singh     82.5     128.0        8.0           218.5
19627   1359531    Rashid Khan     82.5     128.0        8.0           218.5
4890     548311      RA Jadeja     37.0     177.0        0.0           214.0
4279     501244       CH Gayle    117.5      95.0        0.0           212.5
3493     501201     SL Malinga      0.0     197.0        8.0           205.0
3686     501212    PC Valthaty     75.5     128.0        0.0           203.5
9131     829731      JP Duminy     48.0     128.0       16.0           192.0

In [16]:
deliveries[
    (deliveries['match_id'] == 336005) & 
    (deliveries['bowler'] == 'Sohail Tanvir')
][['over', 'ball', 'total_runs', 'is_wicket', 'dismissal_kind']].to_string()

'      over  ball  total_runs  is_wicket dismissal_kind\n5479     0     1           0          1            lbw\n5480     0     2           0          0            NaN\n5481     0     3           1          0            NaN\n5482     0     4           0          0            NaN\n5483     0     5           0          1            lbw\n5484     0     6           0          0            NaN\n5492     2     1           0          0            NaN\n5493     2     2           0          0            NaN\n5494     2     3           1          0            NaN\n5495     2     4           0          0            NaN\n5496     2     5           0          1         caught\n5497     2     6           1          0            NaN\n5576    16     1           0          1         bowled\n5577    16     2           0          0            NaN\n5578    16     3           0          0            NaN\n5579    16     4           0          1         bowled\n5580    16     5           0          0            NaN\n5581    16     6           1          0            NaN\n5589    18     1           0          0            NaN\n5590    18     2           1          0            NaN\n5591    18     3           4          0            NaN\n5592    18     4           4          0            NaN\n5593    18     5           2          0            NaN\n5594    18     6           0          1         bowled'

In [17]:
deliveries[
    (deliveries['match_id'] == 598027) & 
    (deliveries['batter'] == 'CH Gayle')
]['batsman_runs'].agg(['sum', 'count'])

sum      175
count     69
Name: batsman_runs, dtype: int64

In [18]:
# Bring in match context
match_context = matches[['id', 'season', 'date', 'venue', 'team1', 'team2', 
                          'toss_winner', 'toss_decision', 'winner']].copy()

fantasy = fantasy.merge(
    match_context, 
    left_on='match_id', 
    right_on='id', 
    how='left'
).drop(columns='id')

# Add a column: which team was this player playing for?
# Get player-team mapping from deliveries
batting_teams = deliveries[['match_id', 'batter', 'batting_team']].rename(
    columns={'batter': 'player', 'batting_team': 'team'}
)
bowling_teams = deliveries[['match_id', 'bowler', 'bowling_team']].rename(
    columns={'bowler': 'player', 'bowling_team': 'team'}
)
player_teams = pd.concat([batting_teams, bowling_teams]).drop_duplicates()

fantasy = fantasy.merge(player_teams, on=['match_id', 'player'], how='left')

# Did the player's team win?
fantasy['won'] = (fantasy['team'] == fantasy['winner']).astype(int)

# Save to disk
fantasy.to_csv('data/fantasy_points.csv', index=False)

print(f"Saved {len(fantasy)} player-match records")
print(f"\nColumns: {list(fantasy.columns)}")
print(f"\nSample:")
print(fantasy.head(5).to_string())

Saved 21507 player-match records

Columns: ['match_id', 'player', 'bat_pts', 'bowl_pts', 'field_pts', 'fantasy_points', 'season', 'date', 'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'team', 'won']

Sample:
   match_id       player  bat_pts  bowl_pts  field_pts  fantasy_points  season        date                  venue                        team1                  team2                  toss_winner toss_decision                 winner                         team  won
0    335982    AA Noffke      5.5      25.0        0.0            30.5    2007  2008-04-18  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders  Royal Challengers Bangalore         field  Kolkata Knight Riders  Royal Challengers Bangalore    0
1    335982   AB Agarkar      0.0      79.0        6.0            85.0    2007  2008-04-18  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders  Royal Challengers Bangalore         field  Kolkata Knight Riders        Kolkata Knight Riders    1
2    335982     AB Dinda      0.0      58.0        0.0            58.0    2007  2008-04-18  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders  Royal Challengers Bangalore         field  Kolkata Knight Riders        Kolkata Knight Riders    1
3    335982      B Akhil     -2.0       0.0        0.0            -2.0    2007  2008-04-18  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders  Royal Challengers Bangalore         field  Kolkata Knight Riders  Royal Challengers Bangalore    0
4    335982  BB McCullum    151.0       0.0        8.0           159.0    2007  2008-04-18  M Chinnaswamy Stadium  Royal Challengers Bangalore  Kolkata Knight Riders  Royal Challengers Bangalore         field  Kolkata Knight Riders        Kolkata Knight Riders    1